@ECHO off

SETLOCAL

SET INSTALL_PATH=%~dp0..\..
SET GENERATOR=Visual Studio 12 2013 Win64
SET DIRNAME=%~dp0..\%GENERATOR%
SET TOOLSET=CTP_Nov2013

IF NOT EXIST "%DIRNAME%" MD "%DIRNAME%"

PUSHD .
CD "%DIRNAME%"
ECHO cmake "-DCMAKE_INSTALL_PREFIX=%INSTALL_PATH%" -G "%GENERATOR%" -T %TOOLSET% ..
cmake "-DCMAKE_INSTALL_PREFIX=%INSTALL_PATH%" -G "%GENERATOR%" -T %TOOLSET% ..
POPD

ENDLOCAL
PAUSE
